name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-node@3dbcda8bc2eb5ec6aa3fbde01feaae3236952db8
      with:
        node-version: 19
        cache: 'npm'
    - run: npm ci
    - run: npm test
